image: node:11

services:
- mariadb:10.3

variables:
  MYSQL_DATABASE: ffw
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

cache:
  paths:
  - node_modules/

stages:
  - install
  - lint
  - test

npm install:
  stage: install
  script:
   - npm install

npm test:
  stage: test
  script:
   - npm test

npm lint:
  stage: lint
  script:
   - npm run lint
